# Permalinks
permalink:        pretty 

# Setup
url:              http://agostontorok.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            'ágoston.török'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  Researcher. Data interpreter. 

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: agostontorok-github-io

# The tags listed as entries in the sidebar
# sidebar_tags:     [teaching, research]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/P1330220.JPG
color:            '#A85641'

author:
  name:           'Agoston Torok'
  twitter:        torokagoston
  github:         agostontorok
  researchgate:   Agoston_Toeroek
  linkedin:       ágoston-török-phd-3841895a
  
# Google services
#google_analytics: UA-84531900-1
