# Permalinks
permalink:        pretty 
encoding: UTF-8

# Setup
url:              http://agostontorok.github.io
repository:        agostontorok/agostontorok.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            'ágoston.török'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
# description:      >
#  Researcher. Data interpreter. 

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: agostontorok-github-io

# The tags listed as entries in the sidebar
# sidebar_tags:     [teaching, research]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/P1330220.JPG
color:            '#A85641'

author:
  name:           'Agoston Torok'
  medium:         torokagoston
  github:         agostontorok
  instagram:      tddcomics
  researchgate:   Agoston_Toeroek
  linkedin:       agoston-torok
  goodreads:      78912108-goston-t-r-k
  
# Google services
#google_analytics: UA-84531900-1

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-commonmark-ghpages
  - jekyll-coffeescript
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Medium Feed Settings
medium_feed_file: _data/medium_feed.json

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
